In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
# Create the Salary dataset
data = {'YearsExperience': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
 'Salary': [50000, 60000, 70000, 80000, 90000, 100000, 110000, 120000, 130000, 140000]}
df = pd.DataFrame(data)

In [3]:
# Identify the independent and target variables
X = df.iloc[:, 0:1].values
Y = df.iloc[:, 1].values

In [4]:
# Split the variables into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [5]:
# Print the training and testing sets
print("X_train:\n", X_train)
print("y_train:\n", Y_train)
print("X_test:\n", X_test)
print("y_test:\n", Y_test)

X_train:
 [[10]
 [ 2]
 [ 7]
 [ 8]
 [ 4]
 [ 1]
 [ 6]]
y_train:
 [140000  60000 110000 120000  80000  50000 100000]
X_test:
 [[3]
 [9]
 [5]]
y_test:
 [ 70000 130000  90000]


In [6]:
# Build a simple linear regression model
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [7]:
# Print the coefficients and intercept
print("Coefficients:", regressor.coef_)
print("Intercept:", regressor.intercept_)

Coefficients: [10000.]
Intercept: 39999.999999999985
